- name: apt
  block:
    - name: "APT: Update repositories cache"
      become: true
      ansible.builtin.apt:
        update_cache: yes

    - name: "APT: Install apt packages"
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ apts }}"

    - name: "APT: Autoclean and autoremove"
      become: true
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes

- name: debs
  block:
    - name: "DEBS: Check if deb already installed"
      ansible.builtin.stat:
        path: "/usr/bin/{{ item.name }}"
      register: debs_status
      loop: "{{ debs }}"

    - name: "DEBS: Install deb packages"
      become: true
      ansible.builtin.apt:
        deb: "{{ item.item.url }}"
        state: present
      loop: "{{ debs_status.results }}"
      when: not item.stat.exists
      loop_control:
        label: "{{ item.item.name }}"

- name: bins_archive
  block:
    - name: "BIN archive: Check if binary already installed"
      ansible.builtin.stat:
        path: "/usr/sbin/{{ item.name }}"
      register: binary_status
      loop: "{{ bins_archive }}"

    - name: "BIN archive: Create temp dir"
      ansible.builtin.file:
        path: "/tmp/bins_archive"
        state: directory
      loop: "{{ binary_status.results }}"
      when: not item.stat.exists

    - name: "BIN archive: Download archives"
      ansible.builtin.get_url:
        url: "{{ item.item.url }}"
        dest: "/tmp/bins_archive/{{ item.item.name }}.archive"
        mode: '0755'
      loop: "{{ binary_status.results }}"
      when: not item.stat.exists
      loop_control:
        label: "{{ item.item.name }}"

    - name: "BIN archive: Extract archives"
      ansible.builtin.unarchive:
        src: "/tmp/bins_archive/{{ item.item.name }}.archive"
        dest: "/tmp/bins_archive"
        remote_src: yes
      loop: "{{ binary_status.results }}"
      when: not item.stat.exists
      loop_control:
        label: "{{ item.item.name }}"

    - name: "BIN archive: Install to /usr/sbin"
      become: true
      ansible.builtin.command:
        cmd: "find /tmp/bins_archive -type f -name {{ item.item.name }} -exec mv {} /usr/sbin \\;"
      loop: "{{ binary_status.results }}"
      when: not item.stat.exists
      loop_control:
        label: "{{ item.item.name }}"

    - name: "BIN archive: Set permissions"
      become: true
      ansible.builtin.file:
        path: "/usr/sbin/{{ item.item.name }}"
        mode: '0755'
        owner: root
        group: root
      loop: "{{ binary_status.results }}"
      when: not item.stat.exists
      loop_control:
        label: "{{ item.item.name }}"

    - name: "BIN archive: Create symlinks if new_name provided"
      become: true
      ansible.builtin.file:
        src: "/usr/sbin/{{ item.item.name }}"
        dest: "/usr/sbin/{{ item.item.new_name }}"
        state: link
      loop: "{{ binary_status.results }}"
      when:
        - not item.stat.exists
        - item.item.new_name is defined
      loop_control:
        label: "{{ item.item.new_name | default(item.item.name) }}"

- name: bins
  block:
    - name: "BIN: Check if binary already installed"
      ansible.builtin.stat:
        path: "/usr/sbin/{{ item.name }}"
      loop: "{{ bins }}"
      register: bin_status

    - name: "BIN: download and install to /usr/sbin"
      become: true
      ansible.builtin.get_url:
        url: "{{ item.item.url }}"
        dest: "/usr/sbin/{{ item.item.name }}"
        mode: '0755'
        owner: root
        group: root
      loop: "{{ bin_status.results }}"
      when: not item.stat.exists
      loop_control:
        label: "{{ item.item.name }}"

- name: appimage
  block:
    - name: "APPIMAGE: Create app dir"
      ansible.builtin.file:
        path: "/home/{{ ansible_env.USER }}/.apps"
        state: directory

    - name: "APPIMAGE: Create desktop dir"
      ansible.builtin.file:
        path: "/home/{{ ansible_env.USER }}/.local/share/applications"
        state: directory

    - name: "APPIMAGE: Check if app already installed"
      ansible.builtin.stat:
        path: "/home/{{ ansible_env.USER }}/.apps/{{ item.name }}"
      loop: "{{ appimage }}"
      register: app_status

    - name: "APPIMAGE: download and install to ~/.apps"
      ansible.builtin.get_url:
        url: "{{ item.item.url }}"
        dest: "/home/{{ ansible_env.USER }}/.apps/{{ item.item.name }}"
        mode: '0755'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
      loop: "{{ app_status.results }}"
      when: not item.stat.exists
      loop_control:
        label: "{{ item.item.name }}"

    - name: "APPIMAGE: Template desktop"
      ansible.builtin.template:
        src: "desktop/{{ item.desktop_name }}.j2"
        dest: "/home/{{ ansible_env.USER }}/.local/share/applications/{{ item.desktop_name }}"
      loop: "{{ appimage }}"
