- name: gnome_extensions
  block:
    - name: "GNOME EXTENSIONS: Check if extension already installed"
      ansible.builtin.stat:
        path: "{{ gnome_extension_dir }}/{{ item.name }}"
      register: extension_status
      loop: "{{ gnome_extensions }}"

    - name: "GNOME EXTENSIONS: Install and enable extensions"
      ansible.builtin.shell: |
        roles/install-gnome-extensions/install-gnome-extensions.sh --enable {{ item.item.id }}
      loop: "{{ extension_status.results }}"
      when: not item.stat.exists
      loop_control:
        label: "{{ item.item.name }}"

#- name: gnome_extensions_zip
#  block:
#    - name: "GNOME EXTENSIONS ZIP: Check if extension already installed"
#      ansible.builtin.stat:
#        path: "{{ gnome_extension_dir }}/{{ item.name }}"
#      register: extension_zip_status
#      loop: "{{ gnome_extensions_zip }}"
#
#    - name: "GNOME EXTENSIONS ZIP: Create temp directory"
#      ansible.builtin.file:
#        path: "{{ gnome_extension_dir }}/temp"
#        state: directory
#      loop: "{{ extension_zip_status.results }}"
#      when: not item.stat.exists
#      loop_control:
#        label: "{{ item.item.name }}"
#
#    - name: "GNOME EXTENSIONS ZIP: Download arhive"
#      ansible.builtin.get_url:
#        url: "{{ item.item.url }}"
#        dest: "{{ gnome_extension_dir }}/temp/{{ item.item.name }}.zip"
#      loop: "{{ extension_zip_status.results }}"
#      when: not item.stat.exists
#      loop_control:
#        label: "{{ item.item.name }}"
#
#    - name: "GNOME EXTENSIONS ZIP: Enable extensions"
#      ansible.builtin.shell: |
#        gnome-extensions install -f {{ gnome_extension_dir }}/temp/{{ item.item.name }}.zip
#      loop: "{{ extension_zip_status.results }}"
#      when: not item.stat.exists
#      loop_control:
#        label: "{{ item.item.name }}"
#
#    - name: "GNOME EXTENSIONS ZIP: custom config for gestureImprovements" #https://github.com/harshadgavali/gnome-gesture-improvements/issues/206#issuecomment-2026336600
#      block:
#        - name: "GNOME EXTENSIONS: Gesture Improvements: Ensure folder exist"
#          ansible.builtin.file:
#            path: "{{ gnome_extension_dir }}/gestureImprovements@gestures/src"
#            state: directory
#
#        - name: "GNOME EXTENSIONS: Gesture Improvements: Copy config"
#          ansible.posix.synchronize:
#            src: "configs/extension-gesture/snapWindow.js"
#            dest: "{{ gnome_extension_dir }}/gestureImprovements@gestures/src/snapWindow.js"
