- name: flatpaks
  block:
    - name: "FLATPAKS: Install repo if not exist "
      become: true
      ansible.builtin.shell: |
        flatpak remote-add --if-not-exists flathub {{ flatpak_repo }}

    - name: "FLATPAKS: Install multiple packages"
      community.general.flatpak:
        name: "{{ item }}"
        state: present
      loop: "{{ flatpaks }}"
