- name: services_enabled
  block:
    - name: "SERVICES: Enable services"
      become: true
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop: "{{ services_enabled }}"
