apts:
  - gnome-software-plugin-flatpak
  - gnome-tweaks
  - evolution
  - gnome-weather
  - mpv
  - neofetch
  - bind9-dnsutils
  - mc
  - adb
  - htop
  - bat
  - geoip-bin
  - flatpak
  - tilix
  - zsh
  - nvtop
  - smartmontools
  - yt-dlp
  - sshpass
  - flameshot
  - wget
  - jq
  - sed
  - unzip
  - timeshift
  - vim
  - tlp
  - tlp-rdw
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

debs:
  - https://repo.yandex.ru/yandex-disk/yandex-disk_latest_amd64.deb

bins_archive: # to /usr/sbin
  - url: https://www.hdsentinel.com/hdslin/hdsentinel-020b-x64.zip
    name: HDSentinel
    new_name: hdsentinel
  - url: https://github.com/ahmetb/kubectx/releases/download/v0.9.5/kubectx_v0.9.5_linux_x86_64.tar.gz
    name: kubectx
  - url: https://github.com/ahmetb/kubectx/releases/download/v0.9.5/kubens_v0.9.5_linux_x86_64.tar.gz
    name: kubens
  - url: https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz
    name: speedtest
  - url: https://get.helm.sh/helm-v3.14.4-linux-amd64.tar.gz
    name: helm

bins: # to /usr/sbin
  - url: https://cdn.dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
    name: kubectl
  - url: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    name: argocd
